export default {
  primary: "primary",
  secondary: "secondary",
  success: "success",
  danger: "danger",
  warning: "warning",
  info: "info",
  light: "light",
  dark: "dark",
  "outline-primary": "outline-primary",
  "outline-secondary": "outline-secondary",
  "outline-success": "outline-success",
  "outline-danger": "outline-danger",
  "outline-warning": "outline-warning",
  "outline-info": "outline-info",
  "outline-light": "outline-light",
  "outline-dark": "outline-dark",
  link: "link",
};
